Docs/refactor project name
initd1/HackAlert pull request #27
Opened 2023-04-09 12:36 UTC by GH-Syn

2023-04-09 16:06 UTC, initd1 requested changes
the email argument in mail.py needs to be changed from 
`breach_checker = EmailBreachChecker(args.ip)` to
`breach_checker = EmailBreachChecker(args.email)`

2023-04-09 16:06 UTC, initd1 commented on main.py
>              breach_checker = EmailBreachChecker(args.ip)
this needs to be args.email

2023-04-10 00:23 UTC, GH-Syn commented on main.py
>              breach_checker = EmailBreachChecker(args.ip)
Done :+1:

2023-04-10 01:20 UTC, initd1 requested changes

2023-04-10 01:20 UTC, initd1 commented on README.md
>  python main.py -h
please update usage to `python hackert.py -h`

2023-04-10 11:02 UTC, initd1 approved these changes

2023-04-10 14:05 UTC, initd1 approved these changes

2023-04-10 14:35 UTC, merged